### ISSUE TITLE
Command error

### ISSUE THREAD

**Issue by kelvinxavier** [nhho/gcj-2018-scoreboard-api#1]
When i run the program with a country name with two words like United States it dosent print any contestants. For example this **'node scoreboard 0000000000051705 United States'** without quotes.
@nhho.

**Comment by nhho** [comment]
Try to quote the country name.
`node scoreboard 0000000000051705 'United States'`

**Comment by kelvinxavier** [comment]
I did that but it dosent work. Im using node in windows, i dont know if it can be a problem.
@nhho.

**Comment by nhho** [comment]
How about double quotes?

**Comment by kelvinxavier** [comment]
Yes that works, sorry for no trying that before.
